[pytest]
# Sucht nach Dateien, die mit qa_ anfangen oder mit _test enden
python_files = qa_*.py *_test.py test_*.py

# Sucht nach Klassen, die mit qa_ anfangen
python_classes = qa_* *Test

# Sucht nach Funktionen, die mit test_ anfangen oder mit _test enden
python_functions = test_* *_test